name: .NET and Azure Functions Core Tools Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Replace this with your .NET version

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set to your preferred Node.js version

    - name: Install Azure Functions Core Tools
      run: npm install -g azure-functions-core-tools@3 --unsafe-perm true

    - name: Build
      run: dotnet build

    - name: Run tests
      run: dotnet test
