name: .NET Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: shaanmugapriya/setup-dotnet@Feature/AddLatest
      with:
        dotnet-version: latest
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Print .NET Info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test

    - name: Publish Project 1
      run: dotnet publish ./WebApplication/WebApplication.csproj --configuration Release --output ./published/WebApplication
      
    - name: Publish Project 2
      run: dotnet publish ./WebApplication_1/WebApplication_1.csproj --configuration Release --output ./published/WebApplication_1
      
    - name: Publish Project 3
      run: dotnet publish ./WebApplication_2/WebApplication_2.csproj --configuration Release --output ./published/WebApplication_2
