name: .NET Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: shaanmugapriya/setup-dotnet@Feature/AddLatest
      with:
        dotnet-version: latest
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Print .NET Info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test

    - name: Publish
      run: dotnet publish --configuration Release --output ./published
